version: '3.8'
services:
  backend:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/wsavolunteer
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=comsc
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.mariadb.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=never
    depends_on:
      - mariadb

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080

  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=comsc
      - MYSQL_DATABASE=wsavolunteer
    ports:
      - "3307:3306"